language: python
python:
  - "3.5"
install:
  - pip install -r boris/requirements.txt
  - pip install tox
  - pip install coveralls
# command to run tests
script:
  - cd boris && tox
after_success: coveralls
